default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
  strict: false

development:
  <<: *default
  database: devine_shop_dev

production:
  <<: *default
  database: devine_shop_prd
