# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 477a84578bfb25a160f0f1e88a4c078de087bfd41433d4a99351f1bf8fba042a65f85df018477e40e1cbd2cb737d721d89d4b98e5d807acfe5cffbeb224eb786

test:
  secret_key_base: 76cec967b9d0b48ae51bec3b5661b6c4bdbe0df0addf238ee7d0e532de5cb0acfebe309140f8ae7177b2ad38e1fda55c871067f8d97db63a741f59352d4626c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
